name: generate_poll
on:
  schedule:
  - cron: '59 15 * * 1,3,5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          WEPOLLUS_PASSWORD: ${{ secrets.WEPOLLUS_PASSWORD }}
        run: |
          python generate_poll.py
      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.1
        with:
          add: 'suggestions.json'
          default_author: github_actions
          message: "updating suggestions.json - addition/removal of suggestions"
